# Generated by Django 5.1.4 on 2024-12-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('persian', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('addedUser', models.CharField(max_length=100)),
            ],
        ),
    ]
